AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  handleLead:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handleLead
      FunctionName: handleLead
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::040552978376:role/service-role/mylambdarole'
  finalizeLead:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.finalizeLead
      FunctionName: finalizeLead
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::040552978376:role/service-role/mylambdarole'
Metadata:
  PESubscriptions:
    NewLead__e: 
      function: index.handleLead
      connections: 
        - 00Dd0000000cve9EAA
        - 00DE0000000aw3qMAA
    LeadProcessed__e:
      function: index.finalizeLead
      connections:
        - 00Dd0000000cve9EAA
    InterestLead__e:
      function: index.notifyLeadWithInterest
      connections:
        - 00Dd0000000cve9EAA
        